services:
  web:
    build: .
    ports:
      - "8080:80"
    restart: always
    environment:
      - VITE_MAIN_API_URL=https://main.apis.furwaz.fr
      - VITE_FILE_API_URL=https://file.apis.furwaz.fr