export default {
    Account: "Account",
    Home: "Home",
    Apps: "Apps",
    Projects: "Projects",
    About: "About",
    Back: "Back",

    // account
    Informations: "Informations",
    Language: "Language",
    Settings: "Settings",
    Theme: "Theme",
    Light: "Light",
    Dark: "Dark",
    System: "System",
    Username: "Username",
    Email: "Email",
    Role: "Role",
    Password: "Password",
    DeleteAccount: "Delete account",
    UpdateInfos: "Update infos",
    OldPassword: "Old password",
    NewPassword: "New password",
    ConfirmPassword: "Confirm password",
    ChangePassword: "Change password",
    DeleteConfirm: "Are you sure you want to delete your account ?<br>This action is irreversible.",

    // apps
    Applications: "Applications",
    FullbowodyDescription: "Track your body with two basic cameras or more",
    FullbowodyLink: "Go to page",
    ConverterDescription: "Convert YouTube videos to any audio / video file !",
    ConverterLink: "Convert videos",
    PiuzleDescription: "Challenge your brain and find the right path to the exit !",
    PiuzleLink: "Play Piuzle",
    ProcessorDescription: "Play with a little processor, make it evolve in his world and fight agains other processors !",
    ProcessorLink: "See the game",

    // projects
    PersonnalProjects: "Personnal projects",
    SchoolProjects: "School projects",
    VybeenDescription: "Listen music and sing with your friends !",
    VybeenLink: "Try Vybeen",
    RobotDescription: "Create your own humanoïd robot, with a 3D printer, an Arduino, and some motors !",
    RobotLink: "See project",
    XRTouchDescription: "Make VR apps feel more real with XRTouch products !",
    XRTouchLink: "What's that ?",
    CocktailsDescription: "Browse and search for cocktails recipes, and save your favorites !",
    CocktailsLink: "Browse cocktails",
    IndicoDescription: "Learn how to use industrial machines thanks to AR / VR !",
    IndicoLink: "Check Indico",
}