export default {
    Account: "Account",
    Home: "Home",
    Apps: "Apps",
    Projects: "Projects",
    About: "About",
    Back: "Back",

    // actions
    Login: "Login",
    Register: "Register",

    // account
    Informations: "Informations",
    Language: "Language",
    Settings: "Settings",
    Theme: "Theme",
    Light: "Light",
    Dark: "Dark",
    System: "System",
    Username: "Username",
    Email: "Email",
    Role: "Role",
    Password: "Password",
    DeleteAccount: "Delete account",
    UpdateInfos: "Update infos",
    OldPassword: "Old password",
    NewPassword: "New password",
    ConfirmPassword: "Confirm password",
    ChangePassword: "Change password",
    DeleteConfirm: "Are you sure you want to delete your account ?<br>This action is irreversible.",
    NotLoggedIn: "You're not logged in !",
    NotLoggedInDesc: "Please login or register to access your account",

    // home
    ApplicationsDesc1: "You want to track your body ? Convert videos ?",
    ApplicationsDesc2: "I have some applications to show you !",
    SeeApps: "See the apps",
    ProjectsDesc1: "You're looking for nice AR/VR techs ? Or want to build your own robot ?",
    ProjectsDesc2: "Some of my projects could interest you !",
    SeeProjects: "See the projects",
    AboutDesc1: "Want to know more about me ?",
    AboutDesc2: "You can check out my skills, my personnal infos, and more !",
    SeeAbout: "See more",

    // apps
    Applications: "Applications",
    FullbowodyDescription: "Track your body with two basic cameras or more",
    FullbowodyLink: "Go to page",
    ConverterDescription: "Convert YouTube videos to any audio / video file !",
    ConverterLink: "Convert videos",
    PiuzleDescription: "Challenge your brain and find the right path to the exit !",
    PiuzleLink: "Play Piuzle",
    ProcessorDescription: "Play with a little processor, make it evolve in his world and fight agains other processors !",
    ProcessorLink: "See the game",

    // projects
    PersonnalProjects: "Personnal projects",
    SchoolProjects: "School projects",
    VybeenDescription: "Listen music and sing with your friends !",
    VybeenLink: "Try Vybeen",
    RobotDescription: "Create your own humanoïd robot, with a 3D printer, an Arduino, and some motors !",
    RobotLink: "See project",
    XRTouchDescription: "Make VR apps feel more real with XRTouch products !",
    XRTouchLink: "What's that ?",
    CocktailsDescription: "Browse and search for cocktails recipes, and save your favorites !",
    CocktailsLink: "Browse cocktails",
    CarshareDescription: "Carpool between friends or strangers thanks to Car Share !",
    CarshareLink: "Let's go !",
    IndicoDescription: "Learn how to use industrial machines thanks to AR / VR !",
    IndicoLink: "Check Indico",

    // about
    AboutMe: "About me",
    AboutFurwaz: "About FurWaz",
    Skills: "Skills",
    PersoHeader: "<======|| Personnal infos ||======>",
    PersoFirstname: "First name : Paul",
    PersoLastname: "Last name : Loisil",
    PersoAge: "Age : 20 years old",
    PersoGenre: "Genre : Male",
    PersoHobbies: "Hobbies : Web design, Game dev, ...",
}