export default {
    Account: "Account",
    Home: "Home",
    Apps: "Apps",
    Projects: "Projects",
    About: "About",
    Back: "Back",

    Informations: "Informations",
    Language: "Language",
    Settings: "Settings",
    Theme: "Theme",
    Light: "Light",
    Dark: "Dark",
    System: "System",
    Username: "Username",
    Email: "Email",
    Role: "Role",
    Password: "Password",
    DeleteAccount: "Delete account",
    UpdateInfos: "Update infos",
    OldPassword: "Old password",
    NewPassword: "New password",
    ConfirmPassword: "Confirm password",
    ChangePassword: "Change password",
    DeleteConfirm: "Are you sure you want to delete your account ?<br>This action is irreversible.",
}