export default {
    Account: "Compte",
    Home: "Accueil",
    Apps: "Applis",
    Projects: "Projets",
    About: "À propos",
    Back: "Retour",

    // account
    Informations: "Informations",
    Language: "Langage",
    Settings: "Paramètres",
    Theme: "Thème",
    Light: "Clair",
    Dark: "Sombre",
    System: "Système",
    Username: "Nom d'utilisateur",
    Email: "Email",
    Role: "Rôle",
    Password: "Mot de passe",
    DeleteAccount: "Supprimer le compte",
    UpdateInfos: "Mettre à jour",
    OldPassword: "Ancien mot de passe",
    NewPassword: "Nouveau mot de passe",
    ConfirmPassword: "Confirmer le mot de passe",
    ChangePassword: "Changer le mot de passe",
    DeleteConfirm: "Êtes-vous sûr de vouloir supprimer votre compte ?<br>Cette action est irréversible.",

    // home
    ApplicationsDesc1: "Vous voulez tracker votre corps ? Convertir des vidéos ?",
    ApplicationsDesc2: "J'ai quelques applications à vous faire voir !",
    SeeApps: "Voir les apps",
    ProjectsDesc1: "Vous cherchez des techs sympa en AR/VR ? Ou voulez faire votre propre robot ?",
    ProjectsDesc2: "Certains de mes projets pourraient vous intéresser !",
    SeeProjects: "Voir les projets",
    AboutDesc1: "Vous voulez en savoir plus sur moi ?",
    AboutDesc2: "Vous pouvez voir mes compétences, mes infos personnelles, et plus encore !",
    SeeAbout: "Voir plus",

    // apps
    Applications: "Applications",
    FullbowodyDescription: "Suivez votre corps avec deux caméras basiques ou plus",
    FullbowodyLink: "Aller à la page",
    ConverterDescription: "Convertissez des vidéos YouTube en n'importe quel fichier audio / vidéo !",
    ConverterLink: "Convertir des vidéos",
    PiuzleDescription: "Défiez votre cerveau et trouvez le bon chemin vers la sortie !",
    PiuzleLink: "Jouer à Piuzle",
    ProcessorDescription: "Jouez avec un petit processeur, faites-le évoluer dans son monde et combattez d'autres processeurs !",
    ProcessorLink: "Voir le jeu",

    // projects
    PersonnalProjects: "Projets personnels",
    SchoolProjects: "Projets scolaires",
    VybeenDescription: "Écoutez de la musique et chantez avec vos amis !",
    VybeenLink: "Essayer Vybeen",
    RobotDescription: "Créez votre propre robot humanoïde, avec une imprimante 3D, un Arduino, et quelques moteurs !",
    RobotLink: "Voir le projet",
    XRTouchDescription: "Rendez vos applications VR plus réelles avec les produits XRTouch !",
    XRTouchLink: "Qu'est-ce que c'est ?",
    CocktailsDescription: "Parcourez et recherchez des recettes de cocktails, et enregistrez vos favorites !",
    CocktailsLink: "Parcourir les cocktails",
    IndicoDescription: "Apprenez à utiliser des machines industrielles grâce à l'AR / VR !",
    IndicoLink: "Voir Indico",

    // about
    AboutMe: "À propos de moi",
    AboutFurwaz: "À propos de Furwaz",
    Skills: "Compétences",
    PersoHeader: "<======|| Informations personnelles ||======>",
    PersoFirstname: "Prénom : Paul",
    PersoLastname: "Nom : Loisil",
    PersoAge: "Âge : 20 ans",
    PersoGenre: "Genre : Homme",
    PersoHobbies: "Passions : Web design, Game dev, ...",
}