export default {
    Account: "Compte",
    Home: "Accueil",
    Apps: "Applis",
    Projects: "Projets",
    About: "À propos",
    Back: "Retour",

    Informations: "Informations",
    Language: "Langage",
    Settings: "Paramètres",
    Theme: "Thème",
    Light: "Clair",
    Dark: "Sombre",
    System: "Système",
    Username: "Nom d'utilisateur",
    Email: "Email",
    Role: "Rôle",
    Password: "Mot de passe",
    DeleteAccount: "Supprimer le compte",
    UpdateInfos: "Mettre à jour",
    OldPassword: "Ancien mot de passe",
    NewPassword: "Nouveau mot de passe",
    ConfirmPassword: "Confirmer le mot de passe",
    ChangePassword: "Changer le mot de passe",
    DeleteConfirm: "Êtes-vous sûr de vouloir supprimer votre compte ?<br>Cette action est irréversible.",
}