export default {
    Profile: () => "My profile",
    Home: () => "Home",
    Apps: () => "Apps",
    Projects: () => "Projects",
    About: () => "About",
    Back: () => "Back",
    Error: () => "Error",

    // actions
    Login: () => "Login",
    Logining: () => "Login",
    Logout: () => "Logout",
    Logouting: () => "Logging out",
    Register: () => "Register",
    Registration: () => "Registration",
    Registering: () => "Registering",
    Edit: () => "Edit",
    Editing: () => "Editing",
    Save: () => "Save",
    Saving: () => "Saving",
    Cancel: () => "Cancel",
    Canceling: () => "Canceling",
    Delete: () => "Delete",
    Deleting: () => "Deleting",
    Update: () => "Update",
    Updating: () => "Updating",

    // not found
    Woops: () => "Woops !",
    NotFound: () => "This page doesn't exist !",
    WhereAmI: () => "But where am I ?",

    // account
    Informations: () => "Informations",
    Language: () => "Language",
    Settings: () => "Settings",
    Theme: () => "Theme",
    Light: () => "Light",
    Dark: () => "Dark",
    System: () => "System",
    Pseudo: () => "Pseudonym",
    Email: () => "Email",
    Role: () => "Role",
    Admin: () => "Administrator",
    User: () => "User",
    Password: () => "Password",
    Confirmation: () => "Confirmation",
    DeleteAccount: () => "Delete account",
    OldPassword: () => "Old password",
    NewPassword: () => "New password",
    ConfirmPassword: () => "Confirm password",
    ChangePassword: () => "Change password",
    PasswordsDontMatch: () => "Passwords don't match",
    DeleteConfirm: () => "Are you sure you want to delete your account ?\nThis action is irreversible.",
    NotLoggedIn: () => "You're not logged in !",
    NotLoggedInDesc: () => "Please login or register to access your account",

    // home
    MyApps: () => "My apps",
    MyAppsDesc: () => "Try one of my apps ! They are all free and open-source tools to help, entertain or educate you !",
    MyAppsBtn: () => "See my apps",
    MyProjects: () => "My projects",
    MyProjectsDesc: () => "I'm working on a lot of projects, from small tools to big games ! Check them out !",
    MyProjectsBtn: () => "See my projects",
    MyAbout: () => "About me",
    MyAboutDesc: () => "I'm a french student in computer science, and I love to invent and create things !",
    MyAboutBtn: () => "See about me",
    ScrollForMore: () => "Scroll for more",

    // about
    AboutMe: () => "About me",
    
    // projects
    MyGames: () => "My Games",
    SchoolProjects: () => "School Projects",
    ToTheTop: () => "ToTheTop",
    ToTheTopDesc: () => "Go as high as you can at the speed of the music without falling off the ladders!",
    ToTheTopBtn: () => "Try the game",
    Obstruct: () => "Obstruct",
    ObstructDesc: () => "Complete all levels without falling into the holes of your game window!",
    ObstructBtn: () => "Give it a shot",
    Steroids: () => "Steroids",
    SteroidsDesc: () => "Kill all enemies without getting hit, watch out for the chorus!",
    SteroidsBtn: () => "Pew Pew time",
    VyBeen: () => "VyBeen",
    VyBeenDesc: () => "Listen and sing music together, thanks to VyBeen!",
    VyBeenBtn: () => "I want to sing!",
    AlgoSnipper: () => "AlgoSniper",
    AlgoSnipperDesc: () => "A VS Code extension for algorithmic programming at The Charlemagne IT Department!",
    AlgoSnipperBtn: () => "What's that all about?",
    Codec: () => "Codec",
    CodecDesc: () => "My own discord bot to keep me company when no one comes to talk to me :'(",
    CodecBtn: () => "I want to see it!",
    XRTouch: () => "XRTouch",
    XRTouchDesc: () => "A physical interaction system with a virtual world through a Meta Quest 2! °o°",
    XRTouchBtn: () => "Show me!",
    WebXR: () => "WebXR",
    WebXRDesc: () => "An online interactive 3D scene, compatible with virtual reality!",
    WebXRBtn: () => "I'm curious",
    Cocktails: () => "Cocktails",
    CocktailsDesc: () => "A cocktail recipe site, for lovers of alcoholic drinks!",
    CocktailsBtn: () => "I want to drink!",

    // apps
    ProjectManagement: () => "Project Management",
    OhWoops: () => "Oh no!",
    NothingInSection: () => "There's nothing in this section! (For now)",
    Technology: () => "Technology",
    Music: () => "Music",
    Other: () => "Other",
    Brainfuck: () => "Brainfuck",
    BrainfuckDesc: () => "A brainfuck interpreter with a nice graphical interface to see behind the scenes!",
    BrainfuckBtn: () => "I like to tinker",
    FyneWav: () => "FyneWav",
    FyneWavDesc: () => "A music creation software, completely free and open-source!",
    FyneWavBtn: () => "I want to try it",
    Furalizer: () => "Furalizer",
    FuralizerDesc: () => "A fully customizable music visualizer made in python!",
    FuralizerBtn: () => "Take a look",
    Quid: () => "Quid",
    QuidDesc: () => "A web application to create, share and play quizzes!",
    QuidBtn: () => "Try the app",
    Converter: () => "Converter",
    ConverterDesc: () => "A Youtube video converter to multiple audio and video formats!",
    ConverterBtn: () => "Oh, that's cool!"
}