export default {
    Account: () => "Account",
    Profile: () => "Profile",
    Security: () => "Security",
    Sessions: () => "Sessions",
    Home: () => "Home",
    Apps: () => "Apps",
    Projects: () => "Projects",
    About: () => "About",
    Back: () => "Back",
    Error: () => "Error",

    // actions
    Login: () => "Login",
    LoggingIn: () => "Logging in",
    LoggedIn: () => "Logged in",
    Logout: () => "Logout",
    LoggingOut: () => "Logging out",
    LoggedOut: () => "Logging out",
    Register: () => "Register",
    Registering: () => "Registering",
    Registered: () => "Registered",
    Connect: () => "Connect",
    Connecting: () => "Connecting",
    Connected: () => "Connected",
    Edit: () => "Edit",
    Editing: () => "Editing",
    Edited: () => "Edited",
    Continue: () => "Continue",
    Continuing: () => "Continuing",
    Continued: () => "Continued",
    Change: () => "Change",
    Changing: () => "Changing",
    Changed: () => "Changed",
    Close: () => "Close",
    Closing: () => "Closing",
    Closed: () => "Closed",
    Save: () => "Save",
    Saving: () => "Saving",
    Saved: () => "Saved",
    Confirm: () => "Confirm",
    Confirming: () => "Confirming",
    Confirmed: () => "Confirmed",
    Cancel: () => "Cancel",
    Canceling: () => "Canceling",
    Canceled: () => "Canceled",
    Delete: () => "Delete",
    Deleting: () => "Deleting",
    Deleted: () => "Deleted",
    Update: () => "Update",
    Updating: () => "Updating",
    Updated: () => "Updated",
    Create: () => "Create",
    Creating: () => "Creating",
    Created: () => "Created",
    Search: () => "Search",
    Searching: () => "Searching",
    Searched: () => "Searched",

    // not found
    Woops: () => "Woops !",
    NotFound: () => "This page doesn't exist !",
    WhereAmI: () => "But where am I ?",

    // profile
    Informations: () => "Informations",
    Language: () => "Language",
    Settings: () => "Settings",
    Theme: () => "Theme",
    Light: () => "Light",
    Dark: () => "Dark",
    System: () => "System",
    Pseudo: () => "Pseudo",
    Email: () => "Email",
    Role: () => "Role",
    Admin: () => "Administrator",
    User: () => "User",
    Default: () => "Default",
    English: () => "English",
    French: () => "French",
    DeleteAccount: () => "Delete account",
    DeleteConfirm: () => "Are you sure you want to delete your account ?\nThis action is irreversible.",
    DeleteAccount: () => "Delete account",
    DeleteAccountConfirm: () => "Are you sure you want to delete your account ?\nThis action is irreversible.",

    // security
    PasswordModification: () => "Password modification",
    Password: () => "Password",
    Confirmation: () => "Confirmation",
    OldPassword: () => "Old password",
    NewPassword: () => "New password",
    ConfirmPassword: () => "Confirm password",
    ChangePassword: () => "Change password",
    PasswordsDontMatch: () => "Passwords don't match",

    // portal
    ConnectedAs: (name) => "Connected as {" + name + "}",
    NoPortalTokenSpecified: () => "No portal token has been specified, can't continue :(",
    AppPortal: () => "Application portal",
    AppPortalDesc1: () => "You can use FurWaz's portal to link a FurWaz's user to your application.\n" +
                         "This will allow you to get the user's informations using the FurWaz's API.\n" +
                         "\n" +
                         "To use FurWaz's portal in your application, you'll have to include FurWaz's portal script in it.\n" +
                         "For websites and web applications, you can also use the script hosted on FurWaz's CDN server.\n" +
                         "Once the script is added, you will be able to create a connection Portal by writing:",
    AppPortalDesc2: () => "Now that the portal has been created, you can open it by calling the open() method:",
    AppPortalDesc3: () => "Once the user connects to the portal, the 'response' event will be triggered.\n" +
                          "To add a listener on those events, use the 'on' method, here's an example:",
    AppPortalDesc4: () => "If anything wrong occurs during the process, the 'error' event will be triggered.\n" +
                          "Like the 'response' event, you can add a listener to the 'error' event to handle those cases:",
    AppPortalCode1: () => "let portal = new FurWaz.Portal(appKey);",
    AppPortalCode2: () => "portal.open();",
    AppPortalCode3: () => "portal.on('response', (infos) => {\n    console.log('Got user infos :', infos);\n});",
    AppPortalCode4: () => "portal.on('error', (err) => {\n    console.error('Portal error :', err);\n});",
    AppPortalUsage: () => "Usage :",
    AppPortalScript: () => "FurWaz's portal scripts :",
    AppPortalScriptDesc: () => "FurWaz's portal scripts are currently available in JavaScript only.\n" +
                               "Support for other languages will be added soon.\n" +
                               "To include the javascript script in your website, add the following line in your HTML file:",
    AppPortalScriptCode: () => "<script src=\"https://cdn.furwaz.fr/api/portal.min.js\"></script>",

    // apps
    YourApps: () => "Your apps",
    CreateApp: () => "Create app",
    AppName: () => "App name",
    AppDescription: () => "App description",
    AppKey: () => "App key",
    DeleteApp: () => "Delete app",
    DeleteAppConfirm: () => "Are you sure you want to delete this app ?\nThis action is irreversible.",
    NoApps: () => "You don't have any apps yet",
    NoAppsDesc: () => "Create an app by clicking on the [Create app] button !",
    LoadingApps: () => "Loading apps",
    LoadingAppsDesc: () => "Please wait while we load your apps",

    // home
    MyApps: () => "My apps",
    MyAppsDesc: () => "Try one of my apps ! They are all free and open-source tools to help, entertain or educate you !",
    MyAppsBtn: () => "See my apps",
    MyProjects: () => "My projects",
    MyProjectsDesc: () => "I'm working on a lot of projects, from small tools to big games ! Check them out !",
    MyProjectsBtn: () => "See my projects",
    MyAbout: () => "About me",
    MyAboutDesc: () => "I'm a french student in computer science, and I love to invent and create things !",
    MyAboutBtn: () => "See about me",
    ScrollForMore: () => "Scroll for more",

    // about
    AboutMe: () => "About me",
    
    // projects
    MyGames: () => "My Games",
    SchoolProjects: () => "School Projects",
    ToTheTop: () => "ToTheTop",
    ToTheTopDesc: () => "Go as high as you can at the speed of the music without falling off the ladders!",
    ToTheTopBtn: () => "Try the game",
    Obstruct: () => "Obstruct",
    ObstructDesc: () => "Complete all levels without falling into the holes of your game window!",
    ObstructBtn: () => "Give it a shot",
    Steroids: () => "Steroids",
    SteroidsDesc: () => "Kill all enemies without getting hit, watch out for the chorus!",
    SteroidsBtn: () => "Pew Pew time",
    VyBeen: () => "VyBeen",
    VyBeenDesc: () => "Listen and sing music together, thanks to VyBeen!",
    VyBeenBtn: () => "I want to sing!",
    AlgoSnipper: () => "AlgoSniper",
    AlgoSnipperDesc: () => "A VS Code extension for algorithmic programming at The Charlemagne IT Department!",
    AlgoSnipperBtn: () => "What's that all about?",
    Codec: () => "Codec",
    CodecDesc: () => "My own discord bot to keep me company when no one comes to talk to me :'(",
    CodecBtn: () => "I want to see it!",
    XRTouch: () => "XRTouch",
    XRTouchDesc: () => "A physical interaction system with a virtual world through a Meta Quest 2! °o°",
    XRTouchBtn: () => "Show me!",
    WebXR: () => "WebXR",
    WebXRDesc: () => "An online interactive 3D scene, compatible with virtual reality!",
    WebXRBtn: () => "I'm curious",
    Cocktails: () => "Cocktails",
    CocktailsDesc: () => "A cocktail recipe site, for lovers of alcoholic drinks!",
    CocktailsBtn: () => "I want to drink!",

    // apps
    ProjectManagement: () => "Project Management",
    OhWoops: () => "Oh no!",
    NothingInSection: () => "There's nothing in this section! (For now)",
    Technology: () => "Technology",
    Music: () => "Music",
    Other: () => "Other",
    Brainfuck: () => "Brainfuck",
    BrainfuckDesc: () => "A brainfuck interpreter with a nice graphical interface to see behind the scenes!",
    BrainfuckBtn: () => "I like to tinker",
    FyneWav: () => "FyneWav",
    FyneWavDesc: () => "A music creation software, completely free and open-source!",
    FyneWavBtn: () => "I want to try it",
    Furalizer: () => "Furalizer",
    FuralizerDesc: () => "A fully customizable music visualizer made in python!",
    FuralizerBtn: () => "Take a look",
    Quid: () => "Quid",
    QuidDesc: () => "A web application to create, share and play quizzes!",
    QuidBtn: () => "Try the app",
    Converter: () => "Converter",
    ConverterDesc: () => "A Youtube video converter to multiple audio and video formats!",
    ConverterBtn: () => "Oh, that's cool!",
    Fullbowody: () => "FullBowody",
    FullbowodyDesc: () => "Track your body in realtime thanks to one or many cameras !",
    FullbowodyBtn: () => "Show me that !",
}