export default {
    Profile: () => "Mon profil",
    Home: () => "Accueil",
    Apps: () => "Applis",
    Projects: () => "Projets",
    About: () => "À propos",
    Back: () => "Retour",
    Error: () => "Erreur",

    // actions
    Login: () => "Se connecter",
    Logining: () => "Connexion",
    Logout: () => "Se déconnecter",
    Logouting: () => "Déconnexion",
    Register: () => "S'inscrire",
    Registration: () => "Inscription",
    Registering: () => "Inscription",
    Connect: () => "Connecter",
    Connecting: () => "Connexion",
    Connected: () => "Connecté",
    Edit: () => "Modifier",
    Editing: () => "Modification",
    Continue: () => "Continuer",
    Change: () => "Changer",
    Changing: () => "Changement",
    Close: () => "Fermer",
    Closing: () => "Fermeture",
    Save: () => "Sauvegarder",
    Saving: () => "Sauvegarde",
    Cancel: () => "Annuler",
    Canceling: () => "Annulation",
    Delete: () => "Supprimer",
    Deleting: () => "Suppression",
    Update: () => "Mettre à jour",
    Updating: () => "Mise à jour",

    // not found
    Woops: () => "Oups !",
    NotFound: () => "Cette page n'existe pas !",
    WhereAmI: () => "Mais où suis-je ?",

    // account
    Informations: () => "Informations",
    Language: () => "Langage",
    Settings: () => "Paramètres",
    Theme: () => "Thème",
    Light: () => "Clair",
    Dark: () => "Sombre",
    System: () => "Système",
    Pseudo: () => "Pseudonyme",
    Email: () => "Email",
    Role: () => "Rôle",
    Admin: () => "Administrateur",
    User: () => "Utilisateur",
    Password: () => "Mot de passe",
    Confirmation: () => "Confirmation",
    DeleteAccount: () => "Supprimer le compte",
    OldPassword: () => "Ancien mot de passe",
    NewPassword: () => "Nouveau mot de passe",
    ConfirmPassword: () => "Confirmer le mot de passe",
    ChangePassword: () => "Changer le mot de passe",
    PasswordsDontMatch: () => "Les mots de passe ne correspondent pas",
    DeleteConfirm: () => "Êtes-vous sûr de vouloir supprimer votre compte ?<br>Cette action est irréversible.",
    NotLoggedIn: () => "Vous n'êtes pas connecté !",
    NotLoggedInDesc: () => "Veuillez vous connecter ou vous inscrire pour accéder à votre compte",

    // portal
    ConnectedAs: (name) => "Connecté en tant que {" + name + "}",
    NoPortalTokenSpecified: () => "Aucun jeton de portail spécifié, impossible de continuer :(",

    // home
    MyApps: () => "Mes applis",
    MyAppsDesc: () => "Essaye une des mes applis ! Elles sont toutes des outils gratuis et open-source pour t'aider, t'amuser ou t'éduquer !",
    MyAppsBtn: () => "Voir mes applis",
    MyProjects: () => "Mes projets",
    MyProjectsDesc: () => "Je travail sur beaucoup de projets, de petits outils à gros jeux ! Va y jeter un oeil !",
    MyProjectsBtn: () => "Voir mes projets",
    MyAbout: () => "À propos de moi",
    MyAboutDesc: () => "Je suis un étudiant Français en Info, et j'adore inventer et créer des trucs !",
    MyAboutBtn: () => "Voir la section",
    ScrollForMore: () => "Défiler pour voir plus",

    // about
    AboutMe: () => "À propos de moi",

    // projects
    MyGames: () => "Mes jeux",
    SchoolProjects: () => "Projets scolaires",
    ToTheTop: () => "ToTheTop",
    ToTheTopDesc: () => "Allez le plus haut possible à la vitesse de la musique sans tomber des échelles !",
    ToTheTopBtn: () => "Tester le jeu",
    Obstruct: () => "Obstruct",
    ObstructDesc: () => "Terminez tous les niveaux sans tomber dans les trous de vôtre fenêtre de jeu !",
    ObstructBtn: () => "Tenter ma chance",
    Steroids: () => "Steroids",
    SteroidsDesc: () => "Tuez tous les ennemis sans vous faire toucher, attention au refrain !",
    SteroidsBtn: () => "Faire piou piou",
    VyBeen: () => "VyBeen",
    VyBeenDesc: () => "Écoutez et chantez de la musique ensemble, grâce à VyBeen !",
    VyBeenBtn: () => "Je veux chanter !",
    AlgoSnipper: () => "AlgoSniper",
    AlgoSnipperDesc: () => "Une extension VS Code pour faire de l'algorithmique à l'IUT Charlemagne !",
    AlgoSnipperBtn: () => "C'est quoi ce truc ?",
    Codec: () => "Codec",
    CodecDesc: () => "Mon propre bot discord pour m'occuper quand personne ne viens me parler :'(",
    CodecBtn: () => "Je veux le voir !",
    XRTouch: () => "XRTouch",
    XRTouchDesc: () => "Un système d'intéraction physique avec un monde virtuel à travers un Meta Quest 2 ! °o°",
    XRTouchBtn: () => "Montre moi ça !",
    WebXR: () => "WebXR",
    WebXRDesc: () => "Un scène 3D intéractive en ligne, compatible avec la réalité virtuelle !",
    WebXRBtn: () => "Je suis curieux",
    Cocktails: () => "Cocktails",
    CocktailsDesc: () => "Un site de recettes de cocktails, pour les amateurs de boissons alcoolisées !",
    CocktailsBtn: () => "Je veux boire !",

    // apps
    ProjectManagement: () => "Gestion de projets",
    OhWoops: () => "Ah zut !",
    NothingInSection: () => "Il n'y a rien dans cette section ! (Pour le moment)",
    Technology: () => "Technologies",
    Music: () => "Musique",
    Other: () => "Autre",
    Brainfuck: () => "BrainFuck",
    BrainfuckDesc: () => "Un interpréteur brainfuck avec une jolie interface graphique pour voir l'envers du décors !",
    BrainfuckBtn: () => "J'aime bidouiller",
    FyneWav: () => "FyneWav",
    FyneWavDesc: () => "Un logiciel de création de musique, entièrement gratuit et open-source !",
    FyneWavBtn: () => "Je veux essayer",
    Furalizer: () => "Furalizer",
    FuralizerDesc: () => "Un visualiseur de musique entièrement personnalisable fait en python !",
    FuralizerBtn: () => "Jeter un oeil",
    Quid: () => "Quid",
    QuidDesc: () => "Une application web pour créer, partager et jouer à des quiz !",
    QuidBtn: () => "Tester l'app",
    Converter: () => "Converter",
    ConverterDesc: () => "Un convertisseur de vidéo Youtube vers plusieurs formats audio, vidéo !",
    ConverterBtn: () => "Oh c'est pas mal ça !",
    Fullbowody: () => "FullBowody",
    FullbowodyDesc: () => "Trackez votre corps en temps réel grâce à une ou plusieurs caméras !",
    FullbowodyBtn: () => "Fais moi voir ça !",
}